#!/usr/bin/env python

Import('env')
Import('env_modules')

env_sqlmemdb = env_modules.Clone()

env_sqlmemdb.add_source_files(env.modules_sources, "*.cpp")
env_sqlmemdb.add_source_files(env.modules_sources, "sqlite/sqlite3.c")
env_sqlmemdb.add_source_files(env.modules_sources, "sqlite/shell.c")
